package classe;
// Generated 2016-12-05 17:18:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Commentaire generated by hbm2java
 */
public class Commentaire  implements java.io.Serializable {


     private Integer idcommentaire;
     private Membre membre;
     private Restaurant restaurant;
     private String contenu;
     private Date datecreation;
     private int note;

    public Commentaire() {
    }

    public Commentaire(Membre membre, Restaurant restaurant, String contenu, Date datecreation, int note) {
       this.membre = membre;
       this.restaurant = restaurant;
       this.contenu = contenu;
       this.datecreation = datecreation;
       this.note = note;
    }
   
    public Integer getIdcommentaire() {
        return this.idcommentaire;
    }
    
    public void setIdcommentaire(Integer idcommentaire) {
        this.idcommentaire = idcommentaire;
    }
    public Membre getMembre() {
        return this.membre;
    }
    
    public void setMembre(Membre membre) {
        this.membre = membre;
    }
    public Restaurant getRestaurant() {
        return this.restaurant;
    }
    
    public void setRestaurant(Restaurant restaurant) {
        this.restaurant = restaurant;
    }
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }
    public Date getDatecreation() {
        return this.datecreation;
    }
    
    public void setDatecreation(Date datecreation) {
        this.datecreation = datecreation;
    }
    public int getNote() {
        return this.note;
    }
    
    public void setNote(int note) {
        this.note = note;
    }




}


