package classe;
// Generated 2016-12-05 17:18:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * Typemembre generated by hbm2java
 */
public class Typemembre  implements java.io.Serializable {


     private Integer idtypemembre;
     private String typemem;
     private Set membres = new HashSet(0);

    public Typemembre() {
    }

	
    public Typemembre(String typemem) {
        this.typemem = typemem;
    }
    public Typemembre(String typemem, Set membres) {
       this.typemem = typemem;
       this.membres = membres;
    }
   
    public Integer getIdtypemembre() {
        return this.idtypemembre;
    }
    
    public void setIdtypemembre(Integer idtypemembre) {
        this.idtypemembre = idtypemembre;
    }
    public String getTypemem() {
        return this.typemem;
    }
    
    public void setTypemem(String typemem) {
        this.typemem = typemem;
    }
    public Set getMembres() {
        return this.membres;
    }
    
    public void setMembres(Set membres) {
        this.membres = membres;
    }
     public Typemembre getClientId(int id)
    {
        Session session = null;
        Typemembre unType = null;
        List<Typemembre> listeType = null;
        
        Transaction tx = null;
        session = HibernateUtil.getSessionFactory().openSession();
       
        try {
            
            tx = session.beginTransaction();
            
            // Liste de tous les livres
            Query typ = session.createQuery("from typemembre where id=:id");
            typ.setInteger("id", id);
            listeType = typ.list();
           
           
        } catch (Exception e) {
            e.printStackTrace();
        }
       
        session.close();
        if (listeType.size()!=0)
        {
            return listeType.get(0);
        }
        else
        {
          return null;
        }
    
    }




}


