package classe;
// Generated 2016-12-05 17:18:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Typecuisine generated by hbm2java
 */
public class Typecuisine  implements java.io.Serializable {


     private Integer idtype;
     private String typecui;
     private Set restaurants = new HashSet(0);
     private Set membres = new HashSet(0);

    public Typecuisine() {
    }

	
    public Typecuisine(String typecui) {
        this.typecui = typecui;
    }
    public Typecuisine(String typecui, Set restaurants, Set membres) {
       this.typecui = typecui;
       this.restaurants = restaurants;
       this.membres = membres;
    }
   
    public Integer getIdtype() {
        return this.idtype;
    }
    
    public void setIdtype(Integer idtype) {
        this.idtype = idtype;
    }
    public String getTypecui() {
        return this.typecui;
    }
    
    public void setTypecui(String typecui) {
        this.typecui = typecui;
    }
    public Set getRestaurants() {
        return this.restaurants;
    }
    
    public void setRestaurants(Set restaurants) {
        this.restaurants = restaurants;
    }
    public Set getMembres() {
        return this.membres;
    }
    
    public void setMembres(Set membres) {
        this.membres = membres;
    }




}


